---
platform: linux
image_resource:
  type: "docker-image"
  source:
    repository: quay.io/ometria/ometria.docker.platform
    tag: latest
    username: ((quay-io-username))
    password: ((quay-io-password))
inputs:
  - name: git_repo
params:
  MAKEFILE_TARGET: unit-test
run:
  dir: git_repo
  path: bash
  args:
    - -ec
    - make "$MAKEFILE_TARGET"
