---
platform: linux
image_resource:
  type: "docker-image"
  source:
    repository: quay.io/ometria/ometria.docker.platform
    tag: latest
inputs:
  - name: git_repo
params:
  MAKEFILE_TARGET: unit-test
run:
  dir: git_repo
  path: bash
  args:
    - -ec
    - |
      echo "Install dev dependencies"
      make dep-deb
      echo "Running ${MAKEFILE_TARGET} tests"
      make "$MAKEFILE_TARGET"
